{{- if .Values.storage.enabled }}
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ include "rstudio.fullname" . }}
  labels:
    {{- include "rstudio.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode | default "ReadWriteOnce"}}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
{{- end }}